# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@babel/parser-7.8.8" = {
      name = "_at_babel_slash_parser";
      packageName = "@babel/parser";
      version = "7.8.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/parser/-/parser-7.8.8.tgz";
        sha512 = "mO5GWzBPsPf6865iIbzNE0AvkKF3NE+2S3eRUpE+FE07BOAkXh6G+GW/Pj01hhXjve1WScbaIO4UlY1JKeqCcA==";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "bluebird-3.7.2" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "3.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-3.7.2.tgz";
        sha512 = "XpNj6GDQzdfW+r2Wnn7xiSAd7TM3jzkxGXBGTtWKuSXv1xUV+azxAm8jdWZN06QTQk+2N2XB9jRDkvbmQmcRtg==";
      };
    };
    "catharsis-0.8.11" = {
      name = "catharsis";
      packageName = "catharsis";
      version = "0.8.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/catharsis/-/catharsis-0.8.11.tgz";
        sha512 = "a+xUyMV7hD1BrDQA/3iPV7oc+6W26BgVJO05PGEoatMyIuPScQKsde6i3YorWX1qs+AZjnJ18NqdKoCtKiNh1g==";
      };
    };
    "concat-stream-1.5.2" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-1.5.2.tgz";
        sha1 = "708978624d856af41a5a741defdd261da752c266";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "depd-1.1.0" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.0.tgz";
        sha1 = "e1bd82c6aab6ced965b97b88b17ed3e528ca18c3";
      };
    };
    "depd-1.1.2" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.2.tgz";
        sha1 = "9bcd52e14c097763e749b274c4346ed2e560b5a9";
      };
    };
    "dottie-1.1.1" = {
      name = "dottie";
      packageName = "dottie";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dottie/-/dottie-1.1.1.tgz";
        sha1 = "45c2a3f48bd6528eeed267a69a848eaaca6faa6a";
      };
    };
    "entities-1.1.2" = {
      name = "entities";
      packageName = "entities";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-1.1.2.tgz";
        sha512 = "f2LZMYl1Fzu7YSBKg+RoROelpOaNrcGmE9AZubeDfrCEia483oW4MI4VyFd5VNHIgQ/7qm1I0wUHK1eJnn2y2w==";
      };
    };
    "escape-string-regexp-2.0.0" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-2.0.0.tgz";
        sha512 = "UpzcLCXolUWcNu5HtVMHYdXJjArjsF9C0aNnquZYY4uW/Vu0miy5YoWvbV345HauVvcAUnpRuhMMcqTcGOY2+w==";
      };
    };
    "generic-pool-2.3.0" = {
      name = "generic-pool";
      packageName = "generic-pool";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/generic-pool/-/generic-pool-2.3.0.tgz";
        sha1 = "fa40f4c1d6fbefeab7e68092b3a0700602bd692e";
      };
    };
    "graceful-fs-4.2.3" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.3.tgz";
        sha512 = "a30VEBm4PEdx1dRB7MFK7BejejvCvBronbLjht+sHuGYj8PHs7M/5Z+rt5lw551vZ7yfTCj4Vuyy3mSJytDWRQ==";
      };
    };
    "inflection-1.12.0" = {
      name = "inflection";
      packageName = "inflection";
      version = "1.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflection/-/inflection-1.12.0.tgz";
        sha1 = "a200935656d6f5f6bc4dc7502e1aecb703228416";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "js2xmlparser-4.0.1" = {
      name = "js2xmlparser";
      packageName = "js2xmlparser";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js2xmlparser/-/js2xmlparser-4.0.1.tgz";
        sha512 = "KrPTolcw6RocpYjdC7pL7v62e55q7qOMHvLX1UCLc5AAS8qeJ6nukarEJAF2KL2PZxlbGueEbINqZR2bDe/gUw==";
      };
    };
    "jsdoc-3.6.3" = {
      name = "jsdoc";
      packageName = "jsdoc";
      version = "3.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsdoc/-/jsdoc-3.6.3.tgz";
        sha512 = "Yf1ZKA3r9nvtMWHO1kEuMZTlHOF8uoQ0vyo5eH7SQy5YeIiHM+B0DgKnn+X6y6KDYZcF7G2SPkKF+JORCXWE/A==";
      };
    };
    "klaw-3.0.0" = {
      name = "klaw";
      packageName = "klaw";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/klaw/-/klaw-3.0.0.tgz";
        sha512 = "0Fo5oir+O9jnXu5EefYbVK+mHMBeEVEy2cmctR1O1NECcCkPRreJKrS6Qt/j3KC2C148Dfo9i3pCmCMsdqGr0g==";
      };
    };
    "linkify-it-2.2.0" = {
      name = "linkify-it";
      packageName = "linkify-it";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/linkify-it/-/linkify-it-2.2.0.tgz";
        sha512 = "GnAl/knGn+i1U/wjBz3akz2stz+HrHLsxMwHQGofCDfPvlf+gDKN58UtfmUquTY4/MXeE2x7k19KQmeoZi94Iw==";
      };
    };
    "lodash-3.10.1" = {
      name = "lodash";
      packageName = "lodash";
      version = "3.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-3.10.1.tgz";
        sha1 = "5bf45e8e49ba4189e17d482789dfd15bd140b7b6";
      };
    };
    "lodash-4.17.15" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.15.tgz";
        sha512 = "8xOcRHvCjnocdS5cpwXQXVzmmh5e5+saE2QGoeQmbKmRS6J3VQppPOIt0MnmE+4xlZoumy0GPG0D0MVIQbNA1A==";
      };
    };
    "markdown-it-8.4.2" = {
      name = "markdown-it";
      packageName = "markdown-it";
      version = "8.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/markdown-it/-/markdown-it-8.4.2.tgz";
        sha512 = "GcRz3AWTqSUphY3vsUqQSFMbgR38a4Lh3GWlHRh/7MRwz8mcu9n2IO7HOh+bXHrR9kOPDl5RNCaEsrneb+xhHQ==";
      };
    };
    "markdown-it-anchor-5.2.5" = {
      name = "markdown-it-anchor";
      packageName = "markdown-it-anchor";
      version = "5.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/markdown-it-anchor/-/markdown-it-anchor-5.2.5.tgz";
        sha512 = "xLIjLQmtym3QpoY9llBgApknl7pxAcN3WDRc2d3rwpl+/YvDZHPmKscGs+L6E05xf2KrCXPBvosWt7MZukwSpQ==";
      };
    };
    "marked-0.7.0" = {
      name = "marked";
      packageName = "marked";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/marked/-/marked-0.7.0.tgz";
        sha512 = "c+yYdCZJQrsRjTPhUx7VKkApw9bwDkNbHUKo1ovgcfDjb2kc8rLuRbIFyXL5WOEUwzSSKo3IXpph2K6DqB/KZg==";
      };
    };
    "mdurl-1.0.1" = {
      name = "mdurl";
      packageName = "mdurl";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdurl/-/mdurl-1.0.1.tgz";
        sha1 = "fe85b2ec75a59037f2adfec100fd6c601761152e";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "minimist-1.1.3" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.1.3.tgz";
        sha1 = "3bedfd91a92d39016fcfaa1c681e8faa1a1efda8";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "moment-2.24.0" = {
      name = "moment";
      packageName = "moment";
      version = "2.24.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment/-/moment-2.24.0.tgz";
        sha512 = "bV7f+6l2QigeBBZSM/6yTNq4P2fNpSWj/0e7jQcy87A8e7o2nAfP/34/2ky5Vw4B9S446EtIhodAzkFCcR4dQg==";
      };
    };
    "moment-timezone-0.5.28" = {
      name = "moment-timezone";
      packageName = "moment-timezone";
      version = "0.5.28";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment-timezone/-/moment-timezone-0.5.28.tgz";
        sha512 = "TDJkZvAyKIVWg5EtVqRzU97w0Rb0YVbfpqyjgu6GwXCAohVRqwZjf4fOzDE6p1Ch98Sro/8hQQi65WDXW5STPw==";
      };
    };
    "nan-2.7.0" = {
      name = "nan";
      packageName = "nan";
      version = "2.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.7.0.tgz";
        sha1 = "d95bf721ec877e08db276ed3fc6eb78f9083ad46";
      };
    };
    "node-uuid-1.4.8" = {
      name = "node-uuid";
      packageName = "node-uuid";
      version = "1.4.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.8.tgz";
        sha1 = "b040eb0923968afabf8d32fb1f17f1167fdab907";
      };
    };
    "process-nextick-args-1.0.7" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz";
        sha1 = "150e20b756590ad3f91093f25a4f2ad8bff30ba3";
      };
    };
    "readable-stream-2.0.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.0.6.tgz";
        sha1 = "8f90341e68a53ccc928788dacfcd11b36eb9b78e";
      };
    };
    "requizzle-0.2.3" = {
      name = "requizzle";
      packageName = "requizzle";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/requizzle/-/requizzle-0.2.3.tgz";
        sha512 = "YanoyJjykPxGHii0fZP0uUPEXpvqfBDxWV7s6GKAiiOsiqhX6vHNyW3Qzdmqp/iq/ExbhaGbVrjB4ruEVSM4GQ==";
      };
    };
    "rsvp-3.1.0" = {
      name = "rsvp";
      packageName = "rsvp";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/rsvp/-/rsvp-3.1.0.tgz";
        sha1 = "19d96e71315f3ddbc57c4c62a6db898adb64d791";
      };
    };
    "semver-5.7.1" = {
      name = "semver";
      packageName = "semver";
      version = "5.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.7.1.tgz";
        sha512 = "sauaDf/PZdVgrLTNYHRtpXa1iRiKcaebiKQ1BJdpQlWH2lCvexQdX55snPFyK7QzpudqbCI0qXFfOasHdyNDGQ==";
      };
    };
    "sequelize-3.17.3" = {
      name = "sequelize";
      packageName = "sequelize";
      version = "3.17.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sequelize/-/sequelize-3.17.3.tgz";
        sha1 = "9c51ee0f36e4e5045c230d3b46807315146dd765";
      };
    };
    "shimmer-1.1.0" = {
      name = "shimmer";
      packageName = "shimmer";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shimmer/-/shimmer-1.1.0.tgz";
        sha1 = "97d7377137ffbbab425522e429fe0aa89a488b35";
      };
    };
    "slasp-0.0.4" = {
      name = "slasp";
      packageName = "slasp";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/slasp/-/slasp-0.0.4.tgz";
        sha1 = "9adc26ee729a0f95095851a5489f87a5258d57a9";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "sqlite3-3.1.13" = {
      name = "sqlite3";
      packageName = "sqlite3";
      version = "3.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/sqlite3/-/sqlite3-3.1.13.tgz";
        sha512 = "JxXKPJnkZ6NuHRojq+g2WXWBt3M1G9sjZaYiHEWSTGijDM3cwju/0T2XbWqMXFmPqDgw+iB7zKQvnns4bvzXlw==";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "strip-json-comments-3.0.1" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-3.0.1.tgz";
        sha512 = "VTyMAUfdm047mwKl+u79WIdrZxtFtn+nBxHeb844XBQ9uMNTuTHdx2hc5RiAJYqwTj3wc/xe5HLSdJSkJ+WfZw==";
      };
    };
    "taffydb-2.6.2" = {
      name = "taffydb";
      packageName = "taffydb";
      version = "2.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/taffydb/-/taffydb-2.6.2.tgz";
        sha1 = "7cbcb64b5a141b6a2efc2c5d2c67b4e150b2a268";
      };
    };
    "toposort-class-1.0.1" = {
      name = "toposort-class";
      packageName = "toposort-class";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/toposort-class/-/toposort-class-1.0.1.tgz";
        sha1 = "7ffd1f78c8be28c3ba45cd4e1a3f5ee193bd9988";
      };
    };
    "typedarray-0.0.6" = {
      name = "typedarray";
      packageName = "typedarray";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray/-/typedarray-0.0.6.tgz";
        sha1 = "867ac74e3864187b1d3d47d996a78ec5c8830777";
      };
    };
    "uc.micro-1.0.6" = {
      name = "uc.micro";
      packageName = "uc.micro";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/uc.micro/-/uc.micro-1.0.6.tgz";
        sha512 = "8Y75pvTYkLJW2hWQHXxoqRgV7qb9B+9vFEtidML+7koHUFapnVJAZ6cKs+Qjz5Aw3aZWHMC6u0wJE3At+nSGwA==";
      };
    };
    "underscore-1.9.2" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.9.2.tgz";
        sha512 = "D39qtimx0c1fI3ya1Lnhk3E9nONswSKhnffBI0gME9C99fYOkNi04xs8K6pePLhvl1frbDemkaBQ5ikWllR2HQ==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "validator-4.9.0" = {
      name = "validator";
      packageName = "validator";
      version = "4.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/validator/-/validator-4.9.0.tgz";
        sha1 = "082ffce2a76148ff07a8e89e9c2ba43aaf12ec4c";
      };
    };
    "wellknown-0.4.2" = {
      name = "wellknown";
      packageName = "wellknown";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wellknown/-/wellknown-0.4.2.tgz";
        sha1 = "9f4dfbc6f57934e0910f7e6b3f43c391162da7f3";
      };
    };
    "wkx-0.2.0" = {
      name = "wkx";
      packageName = "wkx";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wkx/-/wkx-0.2.0.tgz";
        sha1 = "76c24f16acd0cd8f93cd34aa331e0f7961256e84";
      };
    };
    "xmlcreate-2.0.3" = {
      name = "xmlcreate";
      packageName = "xmlcreate";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlcreate/-/xmlcreate-2.0.3.tgz";
        sha512 = "HgS+X6zAztGa9zIK3Y3LXuJes33Lz9x+YyTxgrkIdabu2vqcGOWwdfCpf1hWLRrd553wd4QCDf6BBO6FfdsRiQ==";
      };
    };
  };
  args = {
    name = "prom2cb";
    packageName = "prom2cb";
    version = "0.0.3";
    src = ./.;
    dependencies = [
      sources."@babel/parser-7.8.8"
      sources."argparse-1.0.10"
      sources."bluebird-3.7.2"
      (sources."catharsis-0.8.11" // {
        dependencies = [
          sources."lodash-4.17.15"
        ];
      })
      sources."concat-stream-1.5.2"
      sources."core-util-is-1.0.2"
      sources."depd-1.1.2"
      sources."dottie-1.1.1"
      sources."entities-1.1.2"
      sources."escape-string-regexp-2.0.0"
      sources."generic-pool-2.3.0"
      sources."graceful-fs-4.2.3"
      sources."inflection-1.12.0"
      sources."inherits-2.0.4"
      sources."isarray-1.0.0"
      sources."js2xmlparser-4.0.1"
      sources."jsdoc-3.6.3"
      sources."klaw-3.0.0"
      sources."linkify-it-2.2.0"
      sources."lodash-3.10.1"
      sources."markdown-it-8.4.2"
      sources."markdown-it-anchor-5.2.5"
      sources."marked-0.7.0"
      sources."mdurl-1.0.1"
      sources."minimist-1.1.3"
      (sources."mkdirp-0.5.1" // {
        dependencies = [
          sources."minimist-0.0.8"
        ];
      })
      sources."moment-2.24.0"
      sources."moment-timezone-0.5.28"
      sources."nan-2.7.0"
      sources."node-uuid-1.4.8"
      sources."process-nextick-args-1.0.7"
      sources."readable-stream-2.0.6"
      (sources."requizzle-0.2.3" // {
        dependencies = [
          sources."lodash-4.17.15"
        ];
      })
      sources."rsvp-3.1.0"
      sources."semver-5.7.1"
      sources."sequelize-3.17.3"
      sources."shimmer-1.1.0"
      sources."slasp-0.0.4"
      sources."sprintf-js-1.0.3"
      sources."sqlite3-3.1.13"
      sources."string_decoder-0.10.31"
      sources."strip-json-comments-3.0.1"
      sources."taffydb-2.6.2"
      sources."toposort-class-1.0.1"
      sources."typedarray-0.0.6"
      sources."uc.micro-1.0.6"
      sources."underscore-1.9.2"
      sources."util-deprecate-1.0.2"
      (sources."validator-4.9.0" // {
        dependencies = [
          sources."depd-1.1.0"
        ];
      })
      sources."wellknown-0.4.2"
      sources."wkx-0.2.0"
      sources."xmlcreate-2.0.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "An adapter library converting Node.js-style functions with callbacks into functions constructing promises and vice-versa";
      license = "MIT";
    };
    production = false;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}